export const LOGIN = "LOGIN",
LOGOUT = "LOGOUT",
SEARCH_VENUE = "SEARCH_VENUE",
LOAD_USERS = "LOAD_USERS",
LOAD_ACTIVITIES = "LOAD_ACTIVITIES",
SAVE_VENUE = "SAVE_VENUE",
LOGGED_IN = "LOGGED_IN",
RENDER_JOINED = "RENDER_JOINED",
ERROR = "ERROR",
OPEN_CHAT = "OPEN_CHAT",
MSG_HISTORY = "MSG_HISTORY",
NEW_MSG = "NEW_MSG"

